### ISSUE TITLE
No enable to run unit test with karma

### ISSUE THREAD

**Issue by hmendezm** [start-angular/SB-Admin-BS4-Angular-4#118]
Hi Guys,

first at all, great job. I was able to run the application. I am trying to run unit test but I get the error below. Do you any idea how to fix this? 

Chrome 60.0.3112 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:42339

Chrome 60.0.3112 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:42339

Best regards
hmendezm

**Comment by Dorian-s** [comment]
Hi, 

FYI, test ran by modifying the test.ts :
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

https://github.com/start-angular/SB-Admin-BS4-Angular-4/issues/126

**Comment by HackPoint** [comment]
@Dorian-s seems that doesn't work. 
`HeadlessChrome 0.0.0 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:43997
HeadlessChrome 0.0.0 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:43997

HeadlessChrome 0.0.0 (Windows 7 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at http://localhost:9876/_karma_webpack_/vendor.bundle.js:43997
`

**Comment by Giusti** [comment]
I just changed the imports to:

import 'zone.js/dist/zone.js';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';

and it worked for me

**Comment by Giusti** [comment]
but it seems i am getting the following error now
```
TypeError: Cannot read property 'assertPresent' of undefined
            at resetFakeAsyncZone C:/Users/Giusti/Projects/testapp/node_modules/@angular/core/@angular/core/testing.es5.js:308:1)
            at Object.<anonymous> C:/Users/Giusti/Projects/testapp/node_modules/@angular/core/@angular/core/testing.es5.js:1015:1)
            at ZoneQueueRunner.webpackJsonp.../../../../zone.js/dist/jasmine-patch.js.jasmine.QueueRunner.ZoneQueueRunner.execute C:/Users/Giusti/Projects/testapp/node_modules/zone.js/dist/jasmine-patch.js:
132:1)
```
for basically all my tests

**Comment by p4pramod** [comment]
Is there any solution for this???

**Comment by boubakar-zeineb** [comment]
i changed my test.ts file as bellow : 

`// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare const __karma__: any;
declare const require: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
// Finally, start Karma to run the tests.
__karma__.start();
`

I was getting it by creating a new project and then copy paste the test.ts file
