### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by lowjumpingfrog** [start-angular/SB-Admin-BS4-Angular-4#146]
I am new to Angular so I could have fouled things up but, I followed the instructions: Did a git clone and then npm run build and got these errors:
ERROR in Error: Template parse errors:
Can't bind to 'up' since it isn't a known property of 'div'. ("
            </div>
            <div class="col text-right">
                <div ngbDropdown [ERROR ->][up]="true" class="d-inline-block">
                    <button class="btn btn-outline-primary" id="d"): ng:///Users/metooo/projects/sps-productivity/sps-site/src/app/layout/bs-component/components/dropdown/dropdown.component.html@15:33
    at Error (native)
    at syntaxError (/Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at TemplateParser.parse (/Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler/bundles/compiler.umd.js:12972:19)
    at AotCompiler._compileComponent (/Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler/bundles/compiler.umd.js:24194:39)
    at /Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler/bundles/compiler.umd.js:24075:55
    at Array.forEach (native)
    at AotCompiler._compileImplFile (/Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler/bundles/compiler.umd.js:24058:20)
    at /Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler/bundles/compiler.umd.js:23969:87
    at Array.map (native)
    at AotCompiler.emitAllImpls (/Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler/bundles/compiler.umd.js:23969:52)
    at CodeGenerator.emit (/Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler-cli/src/codegen.js:42:46)
    at /Users/metooo/projects/sps-productivity/sps-site/node_modules/@angular/compiler-cli/src/codegen.js:33:61
    at process._tickCallback (internal/process/next_tick.js:109:7)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sb-admin-cli-update@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sb-admin-cli-update@0.0.0 build script 'ng build --prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sb-admin-cli-update package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sb-admin-cli-update
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sb-admin-cli-update
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/metooo/projects/sps-productivity/sps-site/npm-debug.log

**Comment by nitinkumarmishra** [comment]
use `placement` instead of `up` refer https://ng-bootstrap.github.io/#/components/dropdown/api
