### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by elmor34** [start-angular/SB-Admin-BS4-Angular-4#85]
When asked for npm start I get 

`

> webpack2-boilerplate@0.0.1 start /Volumes/Work/Angular/webpack2-boilerplate-master
> babel-node ./server --hot
/Volumes/Work/Angular/webpack2-boilerplate-master/src/logger/logger.js:223
var logger = new Proxy({}, {
                 ^
ReferenceError: Proxy is not defined
    at Object.<anonymous> (/Volumes/Work/Angular/webpack2-boilerplate-master/src/logger/logger.js:141:20)
    at Module._compile (module.js:413:34)
    at loader (/Volumes/Work/Angular/webpack2-boilerplate-master/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Work/Angular/webpack2-boilerplate-master/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Volumes/Work/Angular/webpack2-boilerplate-master/src/config/config-builder.js:9:1)
    at Module._compile (module.js:413:34)
`

**Comment by nitinkumarmishra** [comment]
provide us more details like system configuration, node and npm version

**Comment by nitinkumarmishra** [comment]
make sure you have dependencies that require Node 6.9.0 or higher, together with NPM 3 or higher.
