### ISSUE TITLE
issue with npm install / start

### ISSUE THREAD

**Issue by Mattymanme** [start-angular/SB-Admin-BS4-Angular-4#97]
It is giving a issue with npm install  and later when I do a npm start it gives a serious error
Both are listed below.

*********************npm install******************************************************
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@
ngular\cli\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\no
e_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@
ngular\cli\node_modules\webpack-dev-server\node_modules\chokidar\node_modules\f
events):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\k
rma\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
)
```

*****************************npm start*******************************************************

```
> sb-admin-angular4-bootstrap4@1.0.0 start C:\Users\456279\Downloads\SB-Admin-BS
4-Angular-4-master\SB-Admin-BS4-Angular-4-master
> ng serve --ec=true

** NG Live Development Server is listening on localhost:4200, open your browser
on http://localhost:4200 **
 10% building modules 0/1 modules 1 active ...dmin-BS4-Angular-4-master\src\main
 10% building modules 1/2 modules 1 active ...BS4-Angular-4-master\src\polyfills
 10% building modules 2/3 modules 1 active ...r\node_modules\chart.js\dist\Chart
 10% building modules 3/4 modules 1 active ...-Angular-4-master\src\styles\app.s
Hash: 7af4ecfb6661438450df
Time: 18876ms
chunk    {0} scripts.bundle.js, scripts.bundle.js.map (scripts) 28 bytes {4} [in
itial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 28 bytes {
4} [initial] [rendered]
chunk    {2}  (styles) 40 bytes {4} [initial] [rendered]
chunk    {3} main.bundle.js, main.bundle.js.map (main) 40 bytes [initial] [rende
red]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [re
ndered]

ERROR in multi script-loader!./~/chart.js/dist/Chart.js
Module not found: Error: Can't resolve 'script-loader' in 'C:\Users\456279\Downl
oads\SB-Admin-BS4-Angular-4-master\SB-Admin-BS4-Angular-4-master'
 @ multi script-loader!./~/chart.js/dist/Chart.js

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localho
st:4200' in 'C:\Users\456279\Downloads\SB-Admin-BS4-Angular-4-master\SB-Admin-BS
4-Angular-4-master'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./~/font-awesome/css/font-awesome.css ./src/styles/app.scss
Module not found: Error: Can't resolve 'postcss-loader' in 'C:\Users\456279\Down
loads\SB-Admin-BS4-Angular-4-master\SB-Admin-BS4-Angular-4-master'
 @ multi ./~/font-awesome/css/font-awesome.css ./src/styles/app.scss

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'C:\Users\456279\Do
wnloads\SB-Admin-BS4-Angular-4-master\SB-Admin-BS4-Angular-4-master'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'C:\Users\456279\Do
wnloads\SB-Admin-BS4-Angular-4-master\SB-Admin-BS4-Angular-4-master'
 @ multi ./src/polyfills.ts

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in 'C:\Users\456279\
  Downloads\SB-Admin-BS4-Angular-4-master\SB-Admin-BS4-Angular-4-master':
  Error: Can't resolve 'raw-loader' in 'C:\Users\456279\Downloads\SB-Admin-BS4-A
  ngular-4-master\SB-Admin-BS4-Angular-4-master'

  - compiler.js:76
    [SB-Admin-BS4-Angular-4-master]/[cli]/[html-webpack-plugin]/lib/compiler.js:
    76:16

  - Compiler.js:280 Compiler.<anonymous>
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/lib/Compiler.js:280:10

  - Compiler.js:480
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/lib/Compiler.js:480:13

  - Tapable.js:138 next
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/[tapable]/lib/Tapable.js:138
    :11

  - CachePlugin.js:62 Compiler.<anonymous>
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/lib/CachePlugin.js:62:5

  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/[tapable]/lib/Tapable.js:142
    :13

  - Compiler.js:477
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/lib/Compiler.js:477:10

  - Tapable.js:138 next
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/[tapable]/lib/Tapable.js:138
    :11

  - suppress-entry-chunks-webpack-plugin.js:35 Compilation.compilation.plugin
    [SB-Admin-BS4-Angular-4-master]/[@angular]/cli/plugins/suppress-entry-chunks
    -webpack-plugin.js:35:17

  - Tapable.js:142 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/[tapable]/lib/Tapable.js:142
    :13

  - Compilation.js:640 self.applyPluginsAsync.err
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/lib/Compilation.js:640:19

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131
    :46

  - Compilation.js:631 self.applyPluginsAsync.err
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/lib/Compilation.js:631:11

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131
    :46

  - Compilation.js:626 self.applyPluginsAsync.err
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/lib/Compilation.js:626:10

  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [SB-Admin-BS4-Angular-4-master]/[cli]/[webpack]/[tapable]/lib/Tapable.js:131
    :46
```

**Comment by AlainD-** [comment]
Check that you are **not** using node 8.0.0 with **npm5**, because there's a lot of failure currently with npm5: See https://github.com/npm/npm/issues/16839 for details.

**Comment by Mattymanme** [comment]
Hi I am using the recommended node 6 with npm 3.

**Comment by nitinkumarmishra** [comment]
use node LTS version it will work fine.

**Comment by ikhsan017** [comment]
I got this instead when running npm start (node 6.9.3, npm 5.0.3)

```
> sb-admin-angular4-bootstrap4@1.0.0 start /Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4
> ng serve --ec=true

ENOENT: no such file or directory, open '/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/schema/loader.json'
Error: ENOENT: no such file or directory, open '/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/schema/loader.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at validateOptions (/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/node_modules/schema-utils/dist/validateOptions.js:35:27)
    at Function.ExtractTextPlugin.extract (/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/node_modules/extract-text-webpack-plugin/index.js:206:3)
    at rules.push.baseRules.map (/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/node_modules/@angular/cli/models/webpack-configs/styles.js:172:66)
    at Array.map (native)
    at Object.getStylesConfig (/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/node_modules/@angular/cli/models/webpack-configs/styles.js:160:33)
    at NgCliWebpackConfig.buildConfig (/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/node_modules/@angular/cli/models/webpack-config.js:21:31)
    at Class.run (/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/node_modules/@angular/cli/tasks/serve.js:37:98)
    at check_port_1.checkPort.then.port (/Volumes/htdocs/www/github/SB-Admin-BS4-Angular-4/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
``

**Comment by nitinkumarmishra** [comment]
try with npm 3.*

**Comment by nitinkumarmishra** [comment]
added support for npm 5
